### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Momollax** [Riotphobia/LobbyReveal#2]
`Waiting for client...

Exception non gérée : System.ComponentModel.Win32Exception: Accès refusé
   à System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   à System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   à System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   à System.Diagnostics.Process.set_EnableRaisingEvents(Boolean value)
   à Ekko.LeagueClientWatcher.<Observe>d__11.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à LobbyReveal.Program.<Main>d__16.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à LobbyReveal.Program.<Main>(String[] args)
`

**Comment by 0xInception** [comment]
Try running as administrator.
