### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by duncandutchgame** [Riotphobia/LobbyReveal#8]
I was wondering if you have a discord for community members.
But my main question is: since you don't have a tab about this I was wondering if using this tool is bannable, ive been seeing people use it and copy it in their lobby, is this a risk of being banned or is it completely legal?

**Comment by lambwheit** [comment]
no this is unbannable able as it's just using the LCU api

**Comment by 0xInception** [comment]
That's a great question, but I don't have a definitive answer, it's on them if they decide to ban or not. In my personal opinion, I don't think that's gonna happen but it's your choice if you wanna risk or not.
